### PR TITLE
Fix: added missing db columns in `issue_save_new.sh`

### LINKED ISSUE #208: Update to `issue_save_new.sh`
After Database schema modification made in `https://github.com/osrf/buildfarm-tools/pull/206`, it is mandatory to update this scriipt to match the columns

### PR DESCRIPTION
**Pull request by miguelgonrod**
PR to fix #208 

changes:
```diff
- sqlite3 ../buildfarmer.db "insert into test_fail_issues values ('$1', '$2', '$3', '$4', 'OPEN')"

+ sqlite3 ../buildfarmer.db "insert into test_fail_issues (error_name, package_name, job_name, github_issue, status, priority, assignee) values ('$1', '$2', '$3', '$4', 'OPEN', '1', '')"
```

### CODE REVIEW

File: database/scripts/issue_save_new.sh [hunk 1]
```diff
@@ -17,5 +17,5 @@ if [ -z "$4" ]; then
 else
     # sql = "insert into test_fail_issues values ('error_name', 'package_name', 'job_name', 'github_issue')"
     echo "insert into test_fail_issues values ('$1', '$2', '$3', '$4', 'OPEN')"
-    sqlite3 ../buildfarmer.db "insert into test_fail_issues values ('$1', '$2', '$3', '$4', 'OPEN')"
+    sqlite3 ../buildfarmer.db "insert into test_fail_issues (error_name, package_name, job_name, github_issue, status, priority, assignee) values ('$1', '$2', '$3', '$4', 'OPEN', '1', '')"
```
Comment (Crola1702) [inline database/scripts/issue_save_new.sh]: We can just skip the priority and assignee fields as they're nullables, so we cal leave them as null


```suggestion
    sqlite3 ../buildfarmer.db "insert into test_fail_issues (error_name, package_name, job_name, github_issue, status) values ('$1', '$2', '$3', '$4', 'OPEN')"
```

**Review by Crola1702 — CHANGES_REQUESTED** [review]
Some changes to keep it consistent with the database
